---
title: "261006_addition"
author: "Ruiting Tong"
date: "2026-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Adding band for d4  
```{r}
source("DMLA_functions.R")
X_d4 = readRDS(file = "d4/data.RDS")

S = t(X_d4)%*%X_d4
diag(S) = apply(X_d4, 2, sum)
for (i in 1:20){
  res_1st = DMLA_order1_cpp_lglik(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2, -0.2, 1, -0.1, -0.1, 1, -0.1, 1), X = X_d4, K = 5, eta0 = 0.2, rho = 0.99, lam = 1, multiplier = 50, A = diag(not_diag(4)), b = c(1-not_diag(4)), scale = nrow(X_d4), message = T, dX = 4, n = nrow(X_d4), S = S, N_samp = 2000)
  if(i == 1){
    res_1sts = matrix(ncol = 20, nrow = length(res_1st$all_log_liklihood))
    res_1sts[,1] =  res_1st$all_log_liklihood
  }
  res_1sts[,i] = res_1st$all_log_liklihood
}
result = rowMeans(res_1sts)
saveRDS(object = res_1sts, file = "./261006_addition/all_log_posterior_1stOrder_p4.RDS")
saveRDS(object = result, file = "./261006_addition/avg_all_log_posterior_1stOrder_p4.RDS")

etas = c(0.01,0.033)
abbrs = c("001","0033")

for(k in 2){
  for (i in 1:20){
    res_1st_MH = DMLA_order1_MH(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2, -0.2, 1, -0.1, -0.1, 1, -0.1, 1), X = X_d4, K = 500, eta0 = etas[k], lam = 1, A = diag(not_diag(4)), b = c(1-not_diag(4)), scale = nrow(X_d4), message = T, dX = 4, n = nrow(X_d4), S = S, N_samp = 2000)
    if(i == 1){
      res_1st_MHs = matrix(ncol = 20, nrow = length(res_1st_MH$log_likelihood))
      res_1st_MHs[,1] =  res_1st_MH$log_likelihood
    }
    res_1st_MHs[,i] = res_1st_MH$log_likelihood
  }
  result = rowMeans(res_1st_MHs)
  saveRDS(object = res_1st_MHs, file = paste("./261006_addition/all_log_posterior_1stOrder_MH_eta", abbrs[k], "_p4.RDS", sep = ""))
  saveRDS(object = result, file = paste("./261006_addition/avg_all_log_posterior_1stOrder_MH_eta", abbrs[k], "_p4.RDS", sep = ""))
}
```

### Adding band for d5 
```{r}
source("DMLA_functions.R")
X_d5 = readRDS(file = "d5/data.RDS")

S = t(X_d5)%*%X_d5
diag(S) = apply(X_d5, 2, sum)
for (i in 1:20){
  res_1st = DMLA_order1_cpp_lglik(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2, -0.2, -0.2, 1, -0.1, -0.1, -0.1, 1, -0.1, -0.1, 1, -0.1, 1), X = X_d5, K = 5, eta0 = 0.2, rho = 0.99, lam = 1, multiplier = 50, A = diag(not_diag(5)), b = c(1-not_diag(5)), scale = nrow(X_d5), message = T, dX = 5, n = nrow(X_d5), S = S, N_samp = 2000)
  if(i == 1){
    res_1sts = matrix(ncol = 20, nrow = length(res_1st$all_log_liklihood))
    res_1sts[,1] =  res_1st$all_log_liklihood
  }
  res_1sts[,i] = res_1st$all_log_liklihood
}
result = rowMeans(res_1sts)
saveRDS(object = res_1sts, file = "./261006_addition/all_log_posterior_1stOrder_p5.RDS")
saveRDS(object = result, file = "./261006_addition/avg_all_log_posterior_1stOrder_p5.RDS")

etas = c(0.01,0.033)
abbrs = c("001","0033")

for(k in 2){
  for (i in 1:20){
    res_1st_MH = DMLA_order1_MH(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2, -0.2, -0.2, 1, -0.1, -0.1, -0.1, 1, -0.1, -0.1, 1, -0.1, 1), X = X_d5, K = 500, eta0 = etas[k], lam = 1, A = diag(not_diag(5)), b = c(1-not_diag(5)), scale = nrow(X_d5), message = T, dX = 5, n = nrow(X_d5), S = S, N_samp = 2000)
    if(i == 1){
      res_1st_MHs = matrix(ncol = 20, nrow = length(res_1st_MH$log_likelihood))
      res_1st_MHs[,1] =  res_1st_MH$log_likelihood
    }
    res_1st_MHs[,i] = res_1st_MH$log_likelihood
  }
  result = rowMeans(res_1st_MHs)
  saveRDS(object = res_1st_MHs, file = paste("./261006_addition/all_log_posterior_1stOrder_MH_eta", abbrs[k], "_p5.RDS", sep = ""))
  saveRDS(object = result, file = paste("./261006_addition/avg_all_log_posterior_1stOrder_MH_eta", abbrs[k], "_p5.RDS", sep = ""))
}
```


### Comparison with MH + MH trace plot d4
```{r}
# X_d5 = readRDS(file = "d5/data.RDS")
# S = t(X_d5)%*%X_d5
# diag(S) = apply(X_d5, 2, sum)

# etas = c(0.005,0.01,0.033,0.05)
# abbrs = c("0005","001","0033","005")
# 
# for(k in 1:4){
#   for (i in 1:20){
#     res_1st_MH = DMLA_order1_MH(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2,-0.2, -0.2, 1, -0.1, -0.1, -0.1, 1, -0.1, -0.1, 1, -0.1, 1), X = X_d5, K = 1000, eta0 = etas[k], lam = 1, A = diag(not_diag(5)), b = c(1-not_diag(5)), scale = nrow(X_d5), message = T, dX = 5, n = nrow(X_d5), S = S, N_samp = 2000)
#     if(i == 1){
#       res_1st_MHs = matrix(ncol = 20, nrow = length(res_1st_MH$log_likelihood))
#       res_1st_MHs[,1] =  res_1st_MH$log_likelihood
#     }
#     res_1st_MHs[,i] = res_1st_MH$log_likelihood
#   }
#   result = rowMeans(res_1st_MHs)
#   # Already saved
#   saveRDS(object = result, file = paste("./d5/261004_addition/all_log_posterior_1stOrder_MH_eta", abbrs[k], ".RDS", sep = ""))
# }

library(latex2exp)
library(ggplot2)

dat = data.frame(list(
  iterations = 1:500,
  y0033lower = apply(readRDS("./261006_addition/all_log_posterior_1stOrder_MH_eta0033_p4.RDS"), 1, quantile, probs = 0.025),
  y0033upper = apply(readRDS("./261006_addition/all_log_posterior_1stOrder_MH_eta0033_p4.RDS"), 1, quantile, probs = 0.975),
  y0033avg = readRDS("./261006_addition/avg_all_log_posterior_1stOrder_MH_eta0033_p4.RDS"),
  y001lower = apply(readRDS("./261006_addition/all_log_posterior_1stOrder_MH_eta001_p4.RDS"), 1, quantile, probs = 0.025),
  y001upper = apply(readRDS("./261006_addition/all_log_posterior_1stOrder_MH_eta001_p4.RDS"), 1, quantile, probs = 0.975),
  y001avg = readRDS("./261006_addition/avg_all_log_posterior_1stOrder_MH_eta001_p4.RDS"),
  ytrue_lower = apply(readRDS("./261006_addition/all_log_posterior_1stOrder_p4.RDS"), 1, quantile, probs = 0.025)[1:500],
  ytrue_upper = apply(readRDS("./261006_addition/all_log_posterior_1stOrder_p4.RDS"), 1, quantile, probs = 0.975)[1:500],
  ytrue_avg = readRDS("./261006_addition/avg_all_log_posterior_1stOrder_p4.RDS")[1:500]))

font_size = 12
My_Theme = theme(axis.title.x = element_text(size = font_size),axis.text.x = element_text(size = font_size),
                 axis.title.y = element_text(angle = 90, size = font_size), axis.text.y = element_text(angle = 90, size = font_size),
                 legend.text = element_text(size = font_size), legend.title = element_text(size = font_size), plot.title = element_text(size = font_size))

p = ggplot(dat) +
  geom_line(aes(x = iterations, y = y0033avg,  color = "033")) +
  geom_line(aes(x = iterations, y = y001avg, color = "001")) +
  geom_line(aes(x = iterations, y = ytrue_avg, color = "000"), alpha = 0.8) +
  geom_ribbon(
    data = dat,
    aes(iterations, ymin = y0033lower, ymax = y0033upper),
    fill = "red",
    alpha = 0.25
  )+
  geom_ribbon(
    data = dat,
    aes(iterations, ymin = y001lower, ymax = y001upper),
    fill = "green",
    alpha = 0.25
  )+
  geom_ribbon(
    data = dat,
    aes(iterations, ymin = ytrue_lower, ymax = ytrue_upper),
    fill = "blue",
    alpha = 0.25
  )+
  labs(title = "Log-posterior: two-loop sFO-MLA vs MLA with MH impelemented by the exchange algorithm, p = 4",
       x = "samples", y = "log-posterior") +
  theme_bw() + theme(
    legend.position = "bottom",
    legend.title = element_text(face = "bold")
  ) + My_Theme + 
  scale_color_manual(
    name = "Algorithm",
    breaks = c( "033", "001", "000"),
    labels = c(
      TeX("MH, $\\eta = 6.6\\times 10^{-5}$"), TeX("MH, $\\eta = 2 \\times 10^{-5}$"),
      TeX("two-loop sFO-MLA, $\\eta_0 = 4\\times 10^{-4}, l_1 = 250, \\beta = 0.99$")
    ),
    values = c("033" = "red",
      "001" = "green",
      "000" = "blue"
    )
  )+ guides(color = guide_legend(nrow = 4, byrow = TRUE))
  
ggsave(filename = "261006_addition/1st_order_MH_vs_two_loop_d4.png", p, width = 8, height = 6 )

# res_best_1stMH = DMLA_order1_MH(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2, 1, -0.1, 1), X = X1, K = length(y), eta0 = 0.033, lam = 1, A = diag(not_diag(3)), b = c(1-not_diag(3)), scale = nrow(X1), message = T, dX = 3, n = nrow(X1), S = S, N_samp = 500)
# 
# saveRDS(object = res_best_1stMH$primal_samples, file = "primal_1stOrder_MH_bst.RDS")
# saveRDS(object = res_best_1stMH$time, file = "time_1stOrder_MH_bst.RDS")
# saveRDS(object = res_best_1stMH$log_acceptance_ratio, file = "log_acceptance_ratio_1stOrder_MH_bst.RDS")
# saveRDS(object = res_best_1stMH$log_likelihood, file = "all_log_liklihood_1stOrder_MH_bst.RDS")
# saveRDS(object = res_best_1stMH$acceptance, file = "acceptance_1stOrder_MH_eta_bst.RDS")

# res_best_1stMH = readRDS("./1st_order_MHbst/primal_1stOrder_MH_bst.RDS")
# res = t(res_best_1stMH)
# it = nrow(res)
# df = as.data.frame(res)
# colnames(df) = paste0("X", 1:6)
# df$iteration = 1:it
# 
# intercepts = c(1, - 0.1, -0.1, 1, -0.1, 1)
# indices = c(11, 12, 13, 22, 23, 33)
# trace_columns <- paste0("X", 1:6)
# for (i in 1:6){
#   y_limits <- range(df[trace_columns[i]], na.rm = TRUE)
# 
#   p <- ggplot(df, aes(x = iteration, y = .data[[trace_columns[i]]])) +
#     geom_line() + 
#     geom_hline(yintercept = intercepts[i], color = "blue")+
#     labs(
#       x = "iterations",
#       y = TeX(paste0("$\\theta_{", indices[i], "}$")),
#       title = TeX(paste0("Trace plot of $\\theta_{", indices[i], "}$: $\\eta = 0.033$"))
#     ) +
#     My_Theme
#   ggsave(filename = paste("first_order_traceplot_MH_theta", indices[i], ".png", sep = ""),
#        plot = p, width = 8, height = 5)
# }

```