---
title: "0731DMLA_clean"
author: "Ruiting Tong"
date: "2026-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# DMLA data
```{r}
source("mla_pgm.R")
n = 500  ## number of samples
lam = 1

d1 = 4
d = d1*(d1+1)/2
theta = matrix(0, d1, d1)  ## True theta0
theta[lower.tri(theta)] = rep(-0.1, 6)
theta[upper.tri(theta)] = theta[lower.tri(theta)]
diag(theta) = rep(1, 4)
X_d4  = PGMsim(n,theta, max_iter =  10000)
#saveRDS(X_d4, file = "d4/data.RDS")
X_d4 = readRDS(file = "d4/data.RDS")

d1 = 5
d = d1*(d1+1)/2
theta = matrix(0, d1, d1)  ## True theta0
theta[lower.tri(theta)] = rep(-0.1, 10)
theta[upper.tri(theta)] = theta[lower.tri(theta)]
diag(theta) = rep(1, 5)
X_d5  = PGMsim(n,theta, max_iter =  10000)
#saveRDS(X_d5, file = "d5/data.RDS")

# rm(d,d1,n,lam)
```

### Functions 
```{r}
source("DMLA_functions.R")
```


```{r}
S = t(X_d4)%*%X_d4
diag(S) = apply(X_d4, 2, sum)

res_1st = DMLA_order1_cpp_lglik(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2,-0.2, 1, -0.1, -0.1, 1, -0.1, 1), X = X_d4, K = 200, eta0 = 0.2, rho = 0.99, lam = 1, multiplier = 50, A = diag(not_diag(4)), b = c(1-not_diag(4)), scale = nrow(X_d4), message = T, dX = 4, n = nrow(X_d4), S = S, N_samp = 2000)

saveRDS(res_1st$primal_samples, "d4/eta02rho099l250_primal.RDS")
saveRDS(res_1st$time, "d4/eta02rho099l250_time.RDS")
saveRDS(res_1st$all_x, "d4/eta02rho099l250_allx.RDS")
saveRDS(res_1st$outer_loop_indices, "d4/eta02rho099l250_outer.RDS")
saveRDS(res_1st$all_log_liklihood, "d4/eta02rho099l250_lglik.RDS")


S = t(X_d5)%*%X_d5
diag(S) = apply(X_d5, 2, sum)

res_2nd = DMLA_order1_cpp_lglik(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2,-0.2,-0.2, 1, -0.1, -0.1, -0.1, 1, -0.1, -0.1, 1, -0.1, 1), X = X_d5, K = 200, eta0 = 0.2, rho = 0.99, lam = 1, multiplier = 50, A = diag(not_diag(5)), b = c(1-not_diag(5)), scale = nrow(X_d5), message = T, dX = 5, n = nrow(X_d5), S = S, N_samp = 500)

saveRDS(res_2nd$primal_samples, "d5/eta02rho099l250small_primal.RDS")
saveRDS(res_2nd$time, "d5/eta02rho099l250small_time.RDS")
saveRDS(res_2nd$all_x, "d5/eta02rho099l250small_allx.RDS")
saveRDS(res_2nd$outer_loop_indices, "d5/eta02rho099l250small_outer.RDS")
saveRDS(res_2nd$all_log_liklihood, "d5/eta02rho099l250small_lglik.RDS")


S = t(X_d5)%*%X_d5
diag(S) = apply(X_d5, 2, sum)
for (i in 1:20){
  res_1st = DMLA_order1_cpp_lglik(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2,-0.2, -0.2, 1, -0.1, -0.1, -0.1, 1, -0.1, -0.1, 1, -0.1, 1), X = X_d5, K = 20, eta0 = 0.2, rho = 0.99, lam = 1, multiplier = 50, A = diag(not_diag(5)), b = c(1-not_diag(5)), scale = nrow(X_d5), message = T, dX = 5, n = nrow(X_d5), S = S, N_samp = 2000)
  if(i == 1){
    res_1sts = matrix(ncol = 20, nrow = length(res_1st$all_log_liklihood))
    res_1sts[,1] =  res_1st$all_log_liklihood
  }
  res_1sts[,i] = res_1st$all_log_liklihood
}

result = rowMeans(res_1sts)

# Already saved 
saveRDS(object = result, file = "./d5/all_log_posterior_1stOrder.RDS")

# Already saved
# saveRDS(object = res_1st$primal_samples, file = "primal_1stOrder.RDS")
# saveRDS(object = res_1st$all_x, file = "allx_1stOrder.RDS")
# saveRDS(object = res_1st$time, file = "time_1stOrder.RDS")
# saveRDS(object = res_1st$outer_loop_indices, file = "outer_1stOrder.RDS")
# saveRDS(object = res_1st$all_log_liklihood, file = "all_log_liklihood_1stOrder.RDS")
# saveRDS(object = res_1st$primal_sample_log_likelihood, file = "primal_lglik_1stOrder.RDS")
```

### Comparison with MH + MH trace plot d4
```{r}
X_d4 = readRDS(file = "d4/data.RDS")
S = t(X_d4)%*%X_d4
diag(S) = apply(X_d4, 2, sum)

etas = c(0.005,0.01,0.033,0.05)
abbrs = c("0005","001","0033","005")

# for(k in 1:4){
#   for (i in 1:20){
#     res_1st_MH = DMLA_order1_MH(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2, -0.2, 1, -0.1, -0.1, 1,  -0.1, 1), X = X_d4, K = 1000, eta0 = etas[k], lam = 1, A = diag(not_diag(4)), b = c(1-not_diag(4)), scale = nrow(X_d4), message = T, dX = 4, n = nrow(X_d4), S = S, N_samp = 2000)
#     if(i == 1){
#       res_1st_MHs = matrix(ncol = 20, nrow = length(res_1st_MH$log_likelihood))
#       res_1st_MHs[,1] =  res_1st_MH$log_likelihood
#     }
#     res_1st_MHs[,i] = res_1st_MH$log_likelihood
#   }
#   result = rowMeans(res_1st_MHs)
#   # Already saved 
#   saveRDS(object = result, file = paste("./d4/all_log_posterior_1stOrder_MH_eta", abbrs[k], ".RDS", sep = ""))
# }

library(latex2exp)
library(ggplot2)

dat = data.frame(list(
  iterations = 1:1000,
  y0005 = readRDS("./d4/all_log_posterior_1stOrder_MH_eta0005.RDS"),
  y005 = readRDS("./d4/all_log_posterior_1stOrder_MH_eta005.RDS"),
  y0033 = readRDS("./d4/all_log_posterior_1stOrder_MH_eta0033.RDS"),
  y001 = readRDS("./d4/all_log_posterior_1stOrder_MH_eta001.RDS"),
  ytrue = readRDS("./d4/all_log_posterior_1stOrder.RDS")[1:1000]))

font_size = 12
My_Theme = theme(axis.title.x = element_text(size = font_size),axis.text.x = element_text(size = font_size),
                 axis.title.y = element_text(angle = 90, size = font_size), axis.text.y = element_text(angle = 90, size = font_size),
                 legend.text = element_text(size = font_size), legend.title = element_text(size = font_size), plot.title = element_text(size = font_size))

p = ggplot(dat[1:500,]) +
  geom_line(aes(x = iterations, y = y0005, color = "0005"))+
  geom_line(aes(x = iterations, y = y005, color = "005")) +
  geom_line(aes(x = iterations, y = y0033,  color = "033")) +
  geom_line(aes(x = iterations, y = y001, color = "001")) +
  geom_line(aes(x = iterations, y = ytrue, color = "000"), linewidth = 1.5, alpha = 0.8) +
  labs(title = "Log-posterior: two-loop sFO-MLA vs MLA with MH impelemented by the exchange algorithm",
       x = "samples", y = "log-posterior") +
  theme(
    legend.position = "bottom",
    legend.title = element_text(face = "bold")
  ) + My_Theme +
  scale_color_manual(
    name = "Algorithm",
    breaks = c("005", "033", "001", "0005", "000"),
    labels = c(
      TeX("MH, $\\eta = 10^{-4}$"),
      TeX("MH, $\\eta = 6.6\\times 10^{-5}$"), TeX("MH, $\\eta = 2 \\times 10^{-5}$"),
      TeX("MH, $\\eta = 10^{-5}$"),
      TeX("two-loop sFO-MLA, $\\eta_0 = 4\\times 10^{-3}, l_1 = 250, \\beta = 0.99$")
    ),
    values = c(
      "005" = "orange", "033" = "red",
      "001" = "green", "0005" = "brown",
      "000" = "blue"
    ) 
  )+ guides(color = guide_legend(nrow = 4, byrow = TRUE))
  
ggsave(filename = "d4/1st_order_MH_vs_two_loop_d4.png", p, width = 8, height = 6 )

# res_best_1stMH = DMLA_order1_MH(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2, 1, -0.1, 1), X = X1, K = length(y), eta0 = 0.033, lam = 1, A = diag(not_diag(3)), b = c(1-not_diag(3)), scale = nrow(X1), message = T, dX = 3, n = nrow(X1), S = S, N_samp = 500)
# 
# saveRDS(object = res_best_1stMH$primal_samples, file = "primal_1stOrder_MH_bst.RDS")
# saveRDS(object = res_best_1stMH$time, file = "time_1stOrder_MH_bst.RDS")
# saveRDS(object = res_best_1stMH$log_acceptance_ratio, file = "log_acceptance_ratio_1stOrder_MH_bst.RDS")
# saveRDS(object = res_best_1stMH$log_likelihood, file = "all_log_liklihood_1stOrder_MH_bst.RDS")
# saveRDS(object = res_best_1stMH$acceptance, file = "acceptance_1stOrder_MH_eta_bst.RDS")

# res_best_1stMH = readRDS("./1st_order_MHbst/primal_1stOrder_MH_bst.RDS")
# res = t(res_best_1stMH)
# it = nrow(res)
# df = as.data.frame(res)
# colnames(df) = paste0("X", 1:6)
# df$iteration = 1:it
# 
# intercepts = c(1, - 0.1, -0.1, 1, -0.1, 1)
# indices = c(11, 12, 13, 22, 23, 33)
# trace_columns <- paste0("X", 1:6)
# for (i in 1:6){
#   y_limits <- range(df[trace_columns[i]], na.rm = TRUE)
# 
#   p <- ggplot(df, aes(x = iteration, y = .data[[trace_columns[i]]])) +
#     geom_line() + 
#     geom_hline(yintercept = intercepts[i], color = "blue")+
#     labs(
#       x = "iterations",
#       y = TeX(paste0("$\\theta_{", indices[i], "}$")),
#       title = TeX(paste0("Trace plot of $\\theta_{", indices[i], "}$: $\\eta = 0.033$"))
#     ) +
#     My_Theme
#   ggsave(filename = paste("first_order_traceplot_MH_theta", indices[i], ".png", sep = ""),
#        plot = p, width = 8, height = 5)
# }

```

### Plot traceplots for 1st order two loop algorithms d5
```{r}
library(ggplot2)
#install.packages("latex2exp")
library(latex2exp)
font_size = 16
My_Theme = theme(axis.title.x = element_text(size = font_size),axis.text.x = element_text(size = font_size),
                 axis.title.y = element_text(angle = 90, size = font_size), axis.text.y = element_text(angle = 90, size = font_size), 
                 legend.text = element_text(size = font_size), legend.title = element_text(size = font_size), plot.title = element_text(size = font_size))
getwd()
res_1st = list(
  all_x = readRDS("./d5/eta02rho099l250_allx.RDS"), 
  outer_loop_indices = readRDS("./d5/eta02rho099l250_outer.RDS"),
  time = readRDS("./d5/eta02rho099l250_time.RDS"),
  log_posterior = readRDS("./d5/eta02rho099l250_lglik.RDS")
)

res = res_1st
it = ncol(res$all_x)
df = data.frame(t(res$all_x))
df$iteration = 1:it
res_1st$all_x[,res_1st$outer_loop_indices]


intercepts = c(1, -0.1, -0.1, -0.1, -0.1, 1, -0.1, -0.1, -0.1, 1, -0.1, -0.1, 1, -0.1, 1)
indices = c(11, 12, 13, 14, 15, 22, 23, 24, 25, 33, 34, 35, 44, 45, 55)
trace_columns <- paste0("X", 1:15)

for (i in 1:15){
  y_limits <- range(df[trace_columns[i]], na.rm = TRUE)
  tick_length <- 0.015 * diff(y_limits)
  tick_df <- data.frame(
    x = res$outer_loop_indices,
    y = y_limits[1],
    yend = y_limits[1] + tick_length
  )

  p <- ggplot(df, aes(x = iteration, y = .data[[trace_columns[i]]])) +
    geom_line() + 
    geom_hline(yintercept = intercepts[i], color = "blue")+
    labs(
      x = "iterations",
      y = TeX(paste0("$\\theta_{", indices[i], "}$")),
      title = TeX(paste0("Trace plot of $\\theta_{", indices[i], "}$: two-loop sFO-MLA, $p = 5, \\eta_0 = 4\\times 10^{-3}, \\beta = 0.99$"))
    ) +
    geom_segment(
      data = tick_df,
      aes(x = x, xend = x, y = y, yend = yend),
      inherit.aes = FALSE,
      color = "red",
      linewidth = 0.4
    )+
    geom_point(data = df[res$outer_loop_indices,],
               col = "red", size = 0.3)+ theme_bw()+
    My_Theme

  
  #ggsave(filename = paste("zeroth_order_unbiased_traceplot_theta", indices[i], ".png", sep = ""),
  #     plot = p, width = 8, height = 5)
  
    
  ggsave(filename = paste("d5/first_order_traceplot_d5_theta", indices[i], ".png", sep = ""),
       plot = p, width = 7, height = 5)
}
```
### Plot traceplots for 1st order two loop algorithms d4
```{r}
library(ggplot2)
#install.packages("latex2exp")
library(latex2exp)
font_size = 16
My_Theme = theme(axis.title.x = element_text(size = font_size),axis.text.x = element_text(size = font_size),
                 axis.title.y = element_text(angle = 90, size = font_size), axis.text.y = element_text(angle = 90, size = font_size), 
                 legend.text = element_text(size = font_size), legend.title = element_text(size = font_size), plot.title = element_text(size = font_size))
getwd()
res_1st = list(
  all_x = readRDS("./d4/eta02rho099l250_allx.RDS"), 
  outer_loop_indices = readRDS("./d4/eta02rho099l250_outer.RDS"),
  time = readRDS("./d4/eta02rho099l250_time.RDS"),
  log_posterior = readRDS("./d4/eta02rho099l250_lglik.RDS")
)

res = res_1st
it = ncol(res$all_x)
df = data.frame(t(res$all_x))
df$iteration = 1:it
res_1st$all_x[,res_1st$outer_loop_indices]


intercepts = c(1, -0.1, -0.1, -0.1, 1, -0.1, -0.1, 1, -0.1, 1)
indices = c(11, 12, 13, 14, 22, 23, 24, 33, 34, 44)
trace_columns <- paste0("X", 1:10)

for (i in 1:10){
  y_limits <- range(df[trace_columns[i]], na.rm = TRUE)
  tick_length <- 0.015 * diff(y_limits)
  tick_df <- data.frame(
    x = res$outer_loop_indices,
    y = y_limits[1],
    yend = y_limits[1] + tick_length
  )

  p <- ggplot(df, aes(x = iteration, y = .data[[trace_columns[i]]])) +
    geom_line() + 
    geom_hline(yintercept = intercepts[i], color = "blue")+
    labs(
      x = "iterations",
      y = TeX(paste0("$\\theta_{", indices[i], "}$")),
      title = TeX(paste0("Trace plot of $\\theta_{", indices[i], "}$: two-loop sFO-MLA, $p = 4, \\eta_0 = 4\\times 10^{-3}, \\beta = 0.99$"))
    ) +
    geom_segment(
      data = tick_df,
      aes(x = x, xend = x, y = y, yend = yend),
      inherit.aes = FALSE,
      color = "red",
      linewidth = 0.4
    )+
    geom_point(data = df[res$outer_loop_indices,],
               col = "red", size = 0.3)+ theme_bw()+
    My_Theme

  
  #ggsave(filename = paste("zeroth_order_unbiased_traceplot_theta", indices[i], ".png", sep = ""),
  #     plot = p, width = 8, height = 5)
  
    
  ggsave(filename = paste("d4/first_order_traceplot_d4_theta", indices[i], ".png", sep = ""),
       plot = p, width = 7, height = 5)
}
```


### Part 9.2 comparison
```{r}
# ncol(res_1st$all_x) == 158229
res_1st_oneloop = DMLA_order1_one_loop(grad = grad_est_acc_cpp, x0 = c(2,-0.2,-0.2, 1, -0.1, 1), X = X1, K = 1500, eta0 = 0.5, lam = 1, multiplier = 50, A = diag(not_diag(3)), b = c(1-not_diag(3)), scale = nrow(X1), message = T, dX = 3, n = nrow(X1), S = S, N_samp = 500)

saveRDS(res_1st_oneloop$samples, file = "res_1st_oneloop_samples.RDS")
saveRDS(res_1st_oneloop$log_likelihood, file = "res_1st_oneloop_log_posterior.RDS")
saveRDS(res_1st_oneloop$time, file = "res_1st_oneloop_time.RDS")


dat = data.frame(list(
  iterations = 1:158229,
  y1 = res_1st_oneloop$samples[1,],
  y2 = readRDS("./1st_order_two_loop/allx_1stOrder.RDS")[1,]))

dat2 = data.frame(list(
  iterations = 1:158229,
  logy1 = t(res_1st_oneloop$log_likelihood),
  logy2 = t(readRDS("./1st_order_two_loop/all_log_liklihood_1stOrder.RDS"))))

font_size = 12
My_Theme = theme(axis.title.x = element_text(size = font_size),axis.text.x = element_text(size = font_size),
                 axis.title.y = element_text(angle = 90, size = font_size), axis.text.y = element_text(angle = 90, size = font_size),
                 legend.text = element_text(size = font_size), legend.title = element_text(size = font_size), plot.title = element_text(size = font_size))

library(ggplot2)
p = ggplot(dat) +
  geom_line(aes(x = iterations, y = y1, color = "005", alpha = 0.5)) +
  geom_line(aes(x = iterations, y = y2,  color = "033", alpha = 0.5)) +
  labs(title = "Traceplot of theta 11",
       x = "iterations", y = "theta 11") +
  theme(
    legend.position = "bottom",
    legend.title = element_text(face = "bold")
  ) + My_Theme +
  scale_color_manual(
    name = "Algorithm",
    breaks = c("005", "033"),
    labels = c(
      TeX("MH, $\\eta = 0.05$"),
      TeX("MH, $\\eta = 0.033$")
    ),
    values = c(
      "005" = "green", "033" = "red"
    )
  )

posterior
ggplot(dat2) +
  geom_line(aes(x = iterations, y = logy1, color = "005", alpha = 0.5)) +
  geom_line(aes(x = iterations, y = logy2,  color = "033", alpha = 0.5)) +
  labs(title = "Log-posterior: first order methods",
       x = "iterations", y = "log-posterior") +
  theme(
    legend.position = "bottom",
    legend.title = element_text(face = "bold")
  ) + My_Theme +
  scale_color_manual(
    name = "Algorithm",
    breaks = c("005", "033"),
    labels = c(
      TeX("MH, $\\eta = 0.05$"),
      TeX("MH, $\\eta = 0.033$")
    ),
    values = c(
      "005" = "green", "033" = "red"
    )
  )
  
ggsave(filename = "1st_order_MH_vs_two_loop.png", p, width = 8, height = 5 )
```


### Compare times
```{r}
readRDS(file = "./1st_order_two_loop/time_1stOrder.RDS")
readRDS(file = "./1st_order_MHbst/time_1stOrder_MH_bst.RDS")


ncol(readRDS(file = "./1st_order_two_loop/allx_1stOrder.RDS"))
ncol(readRDS(file = "./1st_order_MHbst/primal_1stOrder_MH_bst.RDS"))
```

