---
title: "W2_calculation_d30"
author: "Ruiting Tong"
date: "2026-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Generate data

```{r}
n = 10000
d = 30
alpha = rep(2,d)
theta = c(rep(0.5/d, 4), rep(1/d, d - 8), rep(1.5/d, 3))
classes = sample(1:d, size = n, prob = c(theta, 1-sum(theta)), replace = T)

x = rnorm(n, mean = 0, sd = 0.2)
x = x + classes
saveRDS(x, file = "experiments/d30/data.RDS")
```

# Generate posterior samples

```{r}
library(Rcpp)
sourceCpp(file = "sFO_MLA_mixture_model.cpp")

A = rbind(-diag(d-1), rep(1,d-1))
b = c(rep(0,d-1), 1)
etas = c(0.01, 0.1, 30) # scaled by n = 10000

# Generate the two-loop sFO-MLA samples
result = DMLA_new_grad_cpp_mix_lglik(theta0 = rep(1/d,d-1), x = x, alpha = alpha, B = 135, eta0 = 30, rho = 0.96, lam = 1, multiplier = 450, A = A, b = b, scale = n, message = T, m = 2500 ,std = 0.2)
saveRDS(result$primal_samples, file = "experiments/d30/eta30rho096m2500_primal.RDS")
saveRDS(result$all_log_liklihood, file = "experiments/d30/eta30rho096m2500_lglik.RDS")
saveRDS(result$time, file = "experiments/d30/eta30rho096m2500_time.RDS")
saveRDS(result$all_x, file = "experiments/d30/eta30rho096m2500_allx.RDS")
saveRDS(result$outer_loop_indices, file = "experiments/d30/eta30rho096m2500_outer.RDS")

## Check length(result$all_log_liklihood) == 85203

# Generate the deterministic MLA samples with etas defined above 
for(i in 1:3){
  result = DMLA_new_grad_cpp_mix_lglik(theta0 = rep(1/d,d-1), x = x, alpha = alpha, B = 85203, eta0 = etas[i], rho = 0.96, lam = 1, multiplier = etas[i], A = A, b = b, scale = n, message = T, m = n ,std = 0.2)
  saveRDS(result$primal_samples, file = paste("experiments/d30/eta", etas[i] ,"_primal.RDS", sep = ""))
  saveRDS(result$all_log_liklihood, file = paste("experiments/d30/eta", etas[i] ,"_lglik.RDS", sep = ""))
  saveRDS(result$time, file = paste("experiments/d30/eta", etas[i] ,"_time.RDS", sep = ""))
  saveRDS(result$all_x, file = paste("experiments/d30/eta", etas[i] ,"_allx.RDS", sep = ""))
  saveRDS(result$outer_loop_indices, file = paste("experiments/d30/eta", etas[i] ,"_outer.RDS", sep = ""))
}

# Generate MH samples
result_MH = DMLA_MIX_MH_order1(theta0 = rep(1/d,d-1), x = x, alpha = alpha, B = 85203, eta0 = 10, lam = 1, A = A, b = b, scale = n, message = F, m = n ,std = 0.2)
saveRDS(result_MH$time, file =  "experiments/d30/MH_time.RDS")
saveRDS(result_MH$primal_samples, file ="experiments/d30/MH_primals.RDS")
saveRDS(result_MH$log_likelihood, file = "experiments/d30/MH_lglik.RDS")
```

# Calculate Wassenstein distance for d = 30

```{r}
outer_loop_ind = readRDS(file =  "experiments/d30/eta30rho096m2500_outer.RDS")
benchmark = readRDS(file =  "experiments/d30/MH_primals.RDS")
two_loop = readRDS(file =  "experiments/d30/eta30rho096m2500_allx.RDS")

X <- t(as.matrix(benchmark))[1:outer_loop_ind[135],]
X <- X[-(1:10000),]
Y <- t(as.matrix(two_loop))

Ws = numeric(135)
for(j in 1:135){
Ysmall = Y[1:outer_loop_ind[j], , drop = FALSE]
  W <- T4transport::swdist(X,Ysmall,p = 2,num_proj = 496)
  Ws[j] = W$distance
  print(j)
}
saveRDS(Ws, file ="experiments/d30/W2_sFO_MLA_eta30.RDS")

abbr = c("001", "01", "30")
for(k in 1:3){
  Ws[2:135] = numeric(134)
  Z = t(readRDS(file =  paste("experiments/d30/eta", abbr[k], "_allx.RDS", sep = "")))
  Z = Z[1:outer_loop_ind[135],]
  for(j in 2:135){
  Zsmall = Z[1:outer_loop_ind, , drop = F]
    W <- T4transport::swdist(X,Zsmall,p = 2,num_proj = 496)
    Ws[j] = W$distance
    print(j)
  }
  saveRDS(Ws, file = paste("experiments/d30/W2_eta", abbr[k], ".RDS", sep = ""))
}
```

# Plot W2 for d = 30
```{r}
font_size = 12
My_Theme = theme(axis.title.x = element_text(size = font_size),axis.text.x = element_text(size = font_size),
                 axis.title.y = element_text(angle = 90, size = font_size), axis.text.y = element_text(angle = 90, size = font_size),
                 legend.text = element_text(size = font_size), legend.title = element_text(size = font_size), plot.title = element_text(size = font_size))

library(ggplot2)
library(latex2exp)

smooth = function(x){
  l = length(x)
  y = numeric(l)
  for(i in 1:l){
    if(i == 1 | i == l){y[i] = x[i]}
    else if (i <= 3| i >= l - 2){y[i] = 1/3*(sum(x[(i-1):(i+1)]))}
    else {y[i] = 1/5*(sum(x[(i-2):(i+2)]))}
  }
  return(y)
}

dat = data.frame(list(
  iterations = 1:135,
  w001 = readRDS("experiments/d30/W2_eta001.RDS"),
  w01 = readRDS("experiments/d30/W2_eta01.RDS"),
  wbig = readRDS("experiments/d30/W2_eta30.RDS"),
  wtrue = readRDS("experiments/d30/W2_sFO_MLA_eta30.RDS")
  )
)

dat_new = dat
dat_new$iterations = dat$iterations - 1
dat_new$w001 = smooth(dat$w001)
dat_new$w01 = smooth(dat$w01)
dat_new$wbig = smooth(dat$wbig)
dat_new$wtrue = smooth(dat$wtrue)

p = ggplot(dat_new) +
geom_line(aes(x = iterations, y = w001, color = "001"), linewidth = 1, alpha = 0.5) +
geom_line(aes(x = iterations, y = w01,  color = "01"), linewidth = 1, alpha = 0.5) +
geom_line(aes(x = iterations, y = wbig, color = "big"), linewidth = 1, alpha = 0.5) +
geom_line(aes(x = iterations, y = wtrue, color = "0"), linewidth = 1, alpha = 0.5) +
labs(title = TeX("$W_2$ distance: MLA vs two-loop sFO-MLA, K=30"),
     x = TeX("$k$ for $T_k + 1$"), y = TeX("$W_2$ distance")) + theme_bw() + 
theme(
  legend.position = "bottom",
  legend.title = element_text(face = "bold")
) + My_Theme +
scale_color_manual(
  name = "Algorithm",
  breaks = c("001", "01", "big", "0"),
  labels = c(
    TeX("MLA, $\\eta = 10^{-6}$"),
    TeX("MLA, $\\eta = 10^{-5}$"), TeX("MLA, $\\eta = 3\\times 10^{-3}$"),
    TeX("two-loop sFO-MLA, $\\eta_0 = 3 \\times 10^{-3}, \\beta = 0.96$",)
  ),
  values = c(
    "001" = "orange", "01" = "red",
    "big" = "green",
    "0" = "blue"
  )
)+ guides(
  color = guide_legend(nrow = 2, byrow = TRUE),
)

ggsave(filename = paste("W2_30.png", sep = ""), p, width = 7, height = 5)
```
