---
title: "091626"
author: "Ruiting Tong"
date: "2026-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Test mini-batch
```{r}
library(Rcpp)
sourceCpp(file = "DMLA_combine_mixture_model.cpp")

etas = c(50,70,80)
dims = c(50,80,100)
n = 10000

for(i in 1:3){
  d = dims[i] 
  A = rbind(-diag(d-1), rep(1,d-1))
  b = c(rep(0,d-1), 1)
  alpha = rep(2,d)
  x = readRDS(paste("experiments/d", dims[i], "/data.RDS", sep = ""))
  result = DMLA_new_grad_cpp_mix_lglik(theta0 = rep(1/d,d-1), x = x, alpha = alpha, B = 85203, eta0 = etas[i], rho = 1, lam = 1, multiplier = etas[i], A = A, b = b, scale = n, message = F, m = n, std = 0.2)
  saveRDS(result$primal_samples, file = paste("experiments/d",dims[i],"/261001_addition/eta", etas[i], "_primal.RDS",sep = ""))
  saveRDS(result$all_log_liklihood, file = paste("experiments/d",dims[i],"/261001_addition/eta", etas[i], "_lglik.RDS",sep = ""))
  saveRDS(result$time, file = paste("experiments/d",dims[i],"/261001_addition/eta", etas[i], "_time.RDS",sep = ""))
  saveRDS(result$all_x, file = paste("experiments/d",dims[i],"/261001_addition/eta", etas[i], "_allx.RDS",sep = ""))
  saveRDS(result$outer_loop_indices, file = paste("experiments/d",dims[i],"/261001_addition/eta", etas[i], "_outer.RDS",sep = ""))
  print(i)
}

# Compute W2

abbr = c("500", "10000")


for(k in 1:2){
  benchmark = readRDS(file =  paste("experiments/d", dims[k], "/MH_primals.RDS", sep = ""))
  outer_loop_ind = readRDS(file =  paste("test_minibatch/eta30rho096m500_outer.RDS", sep = ""))
  X <- t(as.matrix(benchmark))[1:outer_loop_ind[135],]
  X <- X[-(1:10000),]
  Z = t(readRDS(file =  paste("experiments/d",dims[k],"/261001_addition/eta", etas[k], "_allx.RDS", sep = "")))
  Z = Z[1:outer_loop_ind[135],]
  
  Ws = numeric(135)
  Ws[1] = readRDS(paste("experiments/d",dims[k],"/d",dims[k],"_additional/W2_eta01.RDS", sep = ""))[1] 
  
  for(j in 2:135){
    Zsmall = Z[1:outer_loop_ind[j], , drop = F]
    W <- T4transport::swdist(X,Zsmall,p = 2,nproj = 100)
    Ws[j] = W$distance
    print(j)
  }
  saveRDS(Ws, file = paste("experiments/d",dims[k],"/261001_addition/W2_eta", etas[k], ".RDS", sep = ""))
}
```
