---
title: "091626"
author: "Ruiting Tong"
date: "2026-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Prepare data
n = 10000
K = 100
alpha = rep(2,K)
theta = c(rep(0.5/K, 4), rep(1/K, K - 8), rep(1.5/K, 3))
classes = sample(1:K, size = n, prob = c(theta, 1-sum(theta)), replace = T)

## p_i's are normal distributions with mean i and std 1.
x = rnorm(n, mean = 0, sd = 0.2)
x = x + classes
```

# With Rcpp
```{r}
library(RcppArmadillo)
sourceCpp(file = "DMLA_combine_mixture_model.cpp")

A = rbind(-diag(K-1), rep(1,K-1))
b = c(rep(0,K-1), 1)

result = DMLA_new_grad_cpp_mix_lglik(theta0 = rep(1/K,K-1), x = x, alpha = alpha, B = 100, eta0 = 0.2, rho = 0.99, lam = 1, multiplier = 100, A = A, b = b, scale = n, message = T, m = 100 ,std = 0.2)

result_MH = DMLA_MIX_MH_order1(theta0 = rep(1/K,K-1), x = x, alpha = alpha, B = length(result$all_log_liklihood), eta0 = 0.01, lam = 1, A = A, b = b, scale = n, message = T, m = 100 ,std = 0.2)
saveRDS(result_MH$primal_samples, file = "K100_MH_std02/B100K100m100eta001lam1_primal.RDS")
saveRDS(result_MH$log_likelihood, file = "K100_MH_std02/B100K100m100eta001lam1_lglik.RDS")
saveRDS(result_MH$time, file = "K100_MH_std02/B100K100m100eta001lam1_time.RDS")
saveRDS(result_MH$acceptance, file = "K100_MH_std02/B100K100m100eta001lam1_accept.RDS")

  times = numeric(10)
for(i in 1:10){
  times[i] = readRDS(file = paste("K",i,"0_std04/B100K",i,"0multiplier100m100eta02rho099lam1_time.RDS",sep = ""))
}

plot(x=10*(1:10),y=times, type = "l",xlab = "dimension",ylab = "time (s)", main = "Runtime vs dimension: B = 100, multiplier = 100, n = 10000, m = 100", ylim = c(0,1100), xlim = c(0,100))
plot(x = 1:length(result$all_log_liklihood), y = result$all_log_liklihood, type = "l", main = "K = 100", ylab = "log_posterior", xlab = "iterations")
points(x = result$outer_loop_indices, y = result$all_log_liklihood[result$outer_loop_indices], col = "red", pch = 16)

plot(y = result$all_x[99,], x = 1:length(result$all_x[99,]), ylab = "theta99", xlab = "iterations", type = "l")
points(x = result$outer_loop_indices, y = result$all_log_liklihood[result$outer_loop_indices], col = "red", pch = 16)


# Comparison with MH
plot(x = 1:length(result_MH$log_likelihood), y = result_MH$log_likelihood, type = "l", main = "K = 100", ylab = "log_posterior", xlab = "iterations", ylim = c(-44200, -44100))
lines(x = 1:length(result$all_log_liklihood), y = result$all_log_liklihood, col = "blue")
points(x = result$outer_loop_indices, y = result$all_log_liklihood[result$outer_loop_indices], col = "red", pch = 16)

result_MH$time
```



## 
##
##
## Compute the gradient with R functions. 
```{r}
evaluate_normal_density = function(s){
  dens = numeric(K)
  for(k in 1:K){
    dens[k] = dnorm(s,mean = k,sd = 0.2)
  }
  return(dens)
}

grad_est = function(m,theta,lam,x){
  theta = c(theta, 1 - sum(theta))
  grad = numeric(K-1)
  indices = sample(1:n, size = m)
  for(j in 1:(K-1)){
    for(i in indices){
      dens = evaluate_normal_density(x[i])
      temp = theta*dens
      grad[j] = grad[j] - (dnorm(x[i],mean = j, sd = 0.2) - dnorm(x[i],mean = K, sd = 0.2))/sum(temp) 
    }
  }
  grad = grad*n/m - (alpha[-K] - 1)*1/theta[-K] + (alpha[K] - 1)/theta[K]
  return(grad)
}

nabla_phi = function(x, lam){
  return(-1/x + rep(1,K-1)*1/(1-sum(x)) + lam*x)
}

## have inverse now
inv_nabla_phi = function(y, lambda, tol = 1e-10) {
  stopifnot(length(y) > 0, all(is.finite(y)),
            length(lambda) == 1, is.finite(lambda), lambda > 0)

  x_of_t <- function(t) {
    a <- y - t
    b <- sqrt(a^2 + 4 * lambda)
    x <- numeric(length(y))
    pos <- a >= 0
    x[pos]  <- (a[pos] + b[pos]) / (2 * lambda)
    x[!pos] <- 2 / (b[!pos] - a[!pos])
    x
  }

  Func <- function(t) sum(x_of_t(t)) + 1 / t - 1
  upper <- 2
  while (Func(upper) > 0) {upper <- 2 * upper}

  t <- uniroot(Func, interval = c(1, upper), tol = tol)$root
  x_of_t(t)
}
```
