---
title: "DMLA_mixed_dist_plots"
author: "Ruiting Tong"
date: "2026-09-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plots for W2 distances
```{r}
font_size = 12
My_Theme = theme(axis.title.x = element_text(size = font_size),axis.text.x = element_text(size = font_size),
                 axis.title.y = element_text(angle = 90, size = font_size), axis.text.y = element_text(angle = 90, size = font_size),
                 legend.text = element_text(size = font_size), legend.title = element_text(size = font_size), plot.title = element_text(size = font_size))

dims = c(30,50,80,100)
outer = 135
init_eta = c(30,50,70,80)
scientific = c(3,5,7,8)
library(ggplot2)
library(latex2exp)

smooth = function(x){
  l = length(x)
  y = numeric(l)
  for(i in 1:l){
    if(i == 1 | i == l){y[i] = x[i]}
    else if (i <= 3| i >= l - 2){y[i] = 1/3*(sum(x[(i-1):(i+1)]))}
    else {y[i] = 1/5*(sum(x[(i-2):(i+2)]))}
  }
  return(y)
}


for(i in 1:4){
  dat = data.frame(list(
    iterations = 1:outer,
    w001 = readRDS(paste("experiments/d",dims[i],"/d",dims[i],"_additional/W2_eta001.RDS", sep = "")),
    w01 = readRDS(paste("experiments/d",dims[i],"/d",dims[i],"_additional/W2_eta01.RDS", sep = "")),
    wbig = readRDS(paste("experiments/d",dims[i],"/d",dims[i],"_additional/W2_eta30.RDS", sep = "")),
    wtrue = readRDS(paste("experiments/d",dims[i],"/d",dims[i],"_additional/W2_sFO_MLA_eta",init_eta[i],".RDS", sep = ""))
    )
  )
  if(i >=2){
    dat$wbig = readRDS(paste("experiments/d",dims[i],"/261001_addition/W2_eta",init_eta[i],".RDS", sep = ""))
  }
  
  dat_new = dat
  dat_new$iterations = dat$iterations - 1
  dat_new$w001 = smooth(dat$w001)
  dat_new$w01 = smooth(dat$w01)
  dat_new$wbig = smooth(dat$wbig)
  dat_new$wtrue = smooth(dat$wtrue)
  dat_new = dat_new[1:125,]
  
  p = ggplot(dat_new) +
  geom_line(aes(x = iterations, y = w001, color = "001"), linewidth = 1, alpha = 0.5) +
  geom_line(aes(x = iterations, y = w01,  color = "01"), linewidth = 1, alpha = 0.5) +
  geom_line(aes(x = iterations, y = wbig, color = "big"), linewidth = 1, alpha = 0.5) +
  geom_line(aes(x = iterations, y = wtrue, color = "0"), linewidth = 1, alpha = 0.5) +
  labs(title = TeX(paste("$W_2$ distance: MLA vs two-loop sFO-MLA, K=", dims[i], sep = "")),
       x = TeX("$k$ for $T_k + 1$"), y = TeX("$W_2$ distance")) + theme_bw() + 
  theme(
    legend.position = "bottom",
    legend.title = element_text(face = "bold")
  ) + My_Theme +
  scale_color_manual(
    name = "Algorithm",
    breaks = c("001", "01", "big", "0"),
    labels = c(
      TeX("MLA, $\\eta = 10^{-6}$"),
      TeX("MLA, $\\eta = 10^{-5}$"), TeX(paste("MLA, $\\eta = ", scientific[i], "\\times 10^{-3}$",sep = "")),
      TeX(paste("two-loop sFO-MLA, $\\eta_0 =", scientific[i] ,"\\times 10^{-3}, \\beta = 0.96$", sep = ""))
    ),
    values = c(
      "001" = "orange", "01" = "red",
      "big" = "green",
      "0" = "blue"
    )
  )+ guides(
    color = guide_legend(nrow = 2, byrow = TRUE),
  )
  
  ggsave(filename = paste("W2_", dims[i], ".png", sep = ""), p, width = 7, height = 5)
}
```



```{r}
times = matrix(ncol = 2, nrow = 4)
times[1,] = c(readRDS("experiments/d30/MH_time.RDS"), readRDS("experiments/d30/d30_additional/eta30rho096m2500_time.RDS"))
times[2,] = c(readRDS("experiments/d50/MH_time.RDS"), readRDS("experiments/d50/d50_additional/eta50rho096m2500_time.RDS"))
times[3,] = c(readRDS("experiments/d80/MH_time.RDS"), readRDS("experiments/d80/d80_additional/eta70rho096m2500_time.RDS"))
times[4,] = c(readRDS("experiments/d100/MH_time.RDS"), readRDS("experiments/d100/d100_additional/eta80rho096m2500_time.RDS"))

times = data.frame(times)
names(times) = c("MH_eta10", "eta_sFO_MLA")
times$dim = c(30,50,80,100)

p = ggplot(times) +
  geom_line(aes(x = dim, y = MH_eta10, color = "MH10"), linewidth = 1, alpha = 0.5) +
  geom_line(aes(x = dim, y = eta_sFO_MLA, color = "0"), linewidth = 1, alpha = 0.5) +
  labs(title = TeX("Runtime: MLA with MH correction vs two-loop sFO-MLA"),
       x = "dimension", y = TeX("runtime (s)")) + theme_bw() + 
  theme(
    legend.position = "bottom",
    legend.title = element_text(face = "bold")
  ) + My_Theme +
  scale_color_manual(
    name = "Algorithm",
    breaks = c("MH10", "0"),
    labels = c(
      TeX("MLA, $\\eta = 10^{-3}$ with MH correction"),
      TeX("two-loop sFO-MLA with mini-batch size 2500 and respective $\\eta_0$'s")
    ),
    values = c(
      "MH10" = "orange",
      "0" = "blue"
    )
  )+ guides(
    color = guide_legend(nrow = 2, byrow = TRUE),
  )
  
   ggsave(filename = paste("runtime.png", sep = ""), p, width = 7, height = 5)
```


